name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install eslint  eslint-plugin-jsdoc@latest --save-dev
    - run: npm run lint
