name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: install gnome-extensions
        run: |
          sudo apt-get update
          sudo apt-get install -y gnome-shell
      - uses: actions/checkout@v4 
      - name: build
        run: |
          make build
        
      - name: publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${GITHUB_REF#refs/tags/} --generate-notes *${GITHUB_REF#refs/tags/}.zip
